version: '3.8'

services:
  vote:
    build: ./vote
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - voting-net

  result:
    build: ./result
    ports:
      - "5001:5001"
    depends_on:
      - db
    networks:
      - voting-net

  worker:
    build: ./worker
    depends_on:
      - redis
      - db
    networks:
      - voting-net

  redis:
    image: redis:latest
    networks:
      - voting-net

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - voting-net
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  voting-net:
    driver: bridge

volumes:
  postgres-data:
